Add load command

diff --git a/desk b/desk
--- a/desk
+++ b/desk
@@ -103,27 +103,10 @@ cmd_go() {
     #   - a directory containing a Deskfile
     #   - empty -> `./Deskfile`
     #
-    local TODESK="$1"
-    local DESKEXT=$(get_deskfile_extension)
-    local DESKPATH="$(find "${DESKS}/" -name "${TODESK}${DESKEXT}" 2>/dev/null)"
 
-    local POSSIBLE_DESKFILE_DIR="${TODESK%$DESKFILE_NAME}"
-    if [ -z "$POSSIBLE_DESKFILE_DIR" ]; then
-      POSSIBLE_DESKFILE_DIR="."
-    fi
-
-    # If nothing could be found in $DESKS/, check to see if this is a path to
-    # a Deskfile.
-    if [[ -z "$DESKPATH" && -d "$POSSIBLE_DESKFILE_DIR" ]]; then
-      if [ ! -f "${POSSIBLE_DESKFILE_DIR}/${DESKFILE_NAME}" ]; then
-        echo "No Deskfile found in '${POSSIBLE_DESKFILE_DIR}'"
-        exit 1
-      fi
-
-      local REALPATH=$( cd $POSSIBLE_DESKFILE_DIR && pwd )
-      DESKPATH="${REALPATH}/${DESKFILE_NAME}"
-      TODESK=$(basename "$REALPATH")
-    fi
+    local RESULT="$(get_desk_name_and_path $1)"
+    local TODESK="${RESULT%:*}"
+    local DESKPATH="${RESULT#*:}"
 
     # Shift desk name so we can forward on all arguments to the shell.
     shift;
@@ -137,6 +120,31 @@ cmd_go() {
     fi
 }
 
+
+cmd_load() {
+    # TODESK ($1) may either be
+    #
+    #   - the name of a desk in $DESKS/
+    #   - a path to a Deskfile
+    #   - a directory containing a Deskfile
+    #   - empty -> `./Deskfile`
+    #
+
+    local RESULT="$(get_desk_name_and_path $1)"
+    local TODESK="${RESULT%:*}"
+    local DESKPATH="${RESULT#*:}"
+
+    # Shift desk name so we can forward on all arguments to the shell.
+    shift;
+
+    if [ -z "$DESKPATH" ]; then
+        echo "Desk $TODESK (${TODESK}${DESKEXT}) not found in $DESKS"
+        exit 1
+    else
+      echo "export DESK_NAME=${TODESK}"
+      echo "export DESK_ENV=${DESKPATH}"
+    fi
+}
 
 cmd_run() {
     local TODESK="$1"
@@ -324,6 +332,32 @@ print_aligned() {
   }'
 }
 
+get_desk_name_and_path() {
+    local TODESK="$1"
+    local DESKEXT=$(get_deskfile_extension)
+    local DESKPATH="$(find "${DESKS}/" -name "${TODESK}${DESKEXT}" 2>/dev/null)"
+
+    local POSSIBLE_DESKFILE_DIR="${TODESK%$DESKFILE_NAME}"
+    if [ -z "$POSSIBLE_DESKFILE_DIR" ]; then
+      POSSIBLE_DESKFILE_DIR="."
+    fi
+
+    # If nothing could be found in $DESKS/, check to see if this is a path to
+    # a Deskfile.
+    if [[ -z "$DESKPATH" && -d "$POSSIBLE_DESKFILE_DIR" ]]; then
+      if [ ! -f "${POSSIBLE_DESKFILE_DIR}/${DESKFILE_NAME}" ]; then
+        echo "No Deskfile found in '${POSSIBLE_DESKFILE_DIR}'"
+        exit 1
+      fi
+
+      local REALPATH=$( cd $POSSIBLE_DESKFILE_DIR && pwd )
+      DESKPATH="${REALPATH}/${DESKFILE_NAME}"
+      TODESK=$(basename "$REALPATH")
+    fi
+
+    echo "${TODESK}:${DESKPATH}"
+}
+
 
 PROGRAM="${0##*/}"
 
@@ -333,6 +367,7 @@ case "$1" in
     version|--version) shift;  cmd_version "$@" ;;
     ls|list) shift;            cmd_list "$@" ;;
     go|.) shift;               cmd_go "$@" ;;
+    load) shift;               cmd_load "$@" ;;
     run) shift;                cmd_run "$@" ;;
     edit) shift;               cmd_edit "$@" ;;
     *)                         cmd_current "$@" ;;
